# Generated by Django 4.1.5 on 2023-01-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
